language: php

php:
  - 5.6
  - 7.0.21
  - 7.1
  - 7.2

env:
  global:
    - setup=basic

matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 ]] ; then phpenv config-rm xdebug.ini; fi
  - mv .env.example .env

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

before_script:
  - php artisan canvas:publish:assets -y
  - php artisan canvas:publish:config -y
  - php artisan key:generate
  - echo '1485524707' > storage/canvas_installed.lock

script:
  - vendor/bin/phpunit