language: php

php:
  - 5.5.9
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - mv .env.example .env

install:
  - /home/travis/.phpenv/versions/5.5.9/bin/composer self-update
  - composer install

before_script:
  - mysql -u root -e 'create database canvas_testing;'
  - export DB_DATABASE=canvas_testing
  - export DB_USERNAME=root
  - export DB_PASSWORD=

script:
  - php artisan key:generate
  - php artisan migrate --seed
  - vendor/bin/phpunit
